pool:
  vmImage: 'macos-latest'
  name: Azure Pipelines
  demands: maven

variables:
  mavenPOMFile: 'pom.xml'

steps:

- task: Maven@3
  displayName: 'Maven pom.xml'
  inputs:
    mavenPomFile: '$(mavenPOMFile)'
    goals: 'clean test -P cross-browser -D env=stage'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenAuthenticateFeed: false
    options: '-e -X'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: 'reports'
  condition: succeededOrFailed()
