#Multi-configuration and multi-agent job options are not exported to YAML. Configure these options using documentation guidance: https://docs.microsoft.com/vsts/pipelines/process/phases

pool:
  name: Azure Pipelines
  demands: maven

variables:
  mavenPOMFile: 'pom.xml'

steps:
- task: Maven@1
  displayName: 'Maven pom.xml'
  inputs:
    versionSpec: '11'
    mavenPomFile: '$(Parameters.mavenPOMFile)'
    goals: 'clean test -P sanity -Denv=qa'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    mavenAuthenticateFeed: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
